# Documentation:  http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.7
  - nightly
codecov: true
matrix:
  allowed_failures:
    - julia: nightly
#    - julia: 1.0
# Work around a Travis bug
git:
  depth: 999999
notifications:
  email: false
sudo: false
#addons:
#    apt_packages:
#        - gfortran
env:
  matrix:
    - JULIA_BarycentricLagrangeInterpolation_BUILD_SOURCE=true
#    - JULIA_BarycentricLagrangeInterpolation_BUILD_SOURCE=false
before_install:
  - pwd
  - export JL_PKG=BarycentricLagrangeInterpolation
#  - pwd
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then brew update >/dev/null 2>&1; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone("https://github.com/LaGuer/BarycentricLagrangeInterpolation.jl"); Pkg.build("BarycentricLagrangeInterpolation")'
#  - julia -e 'Pkg.build("BarycentricLagrangeInterpolation")'
#  - julia -e 'Pkg.test("BarycentricLagrangeInterpolation"; coverage=false)'
after_success:
  - echo $TRAVIS_JULIA_VERSION
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
#  - julia -e 'cd(Pkg.dir("BarycentricLagrangeInterpolation")); ps=Pkg.PackageSpec(name="Documenter", version="0.21"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))'
  - julia -e 'import Pkg; Pkg.clone("https://github.com/LaGuer/BarycentricLagrangeInterpolation"); ps=Pkg.PackageSpec(name="Documenter", version="0.21"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))'
  - julia -e 'import Pkg; Pkg.status(); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: 
        - linux
      allowed_failures:
        - julia: nightly
      script:
        - julia --project=@ -e 'import Pkg; Pkg.add("Documenter")'
        - julia --project=@ -e 'import Pkg; Pkg.add("Measurements")'
        - julia --project=@ -e 'import Pkg; Pkg.add("Unitful")'
        - julia --project=@ -e 'import Pkg; Pkg.add("PyCall")'
        - julia --project=@ --color=yes -e 'using Pkg; Pkg.build()'
        - julia --project=@ -e 'import Pkg; Pkg.status()'
        - julia --project=@ -e 'import Pkg; Pkg.build()'
        - julia --project=@ -e 'using Pkg; Pkg.instantiate()'
#        - julia --project=@ -e 'import Pkg; Pkg.add("BarycentricLagrangeInterpolation")'
#        - julia --project=@ -e 'import Pkg; Pkg.clone("https://github.com/LaGuer/BarycentricLagrangeInterpolation")'
#        - julia --project=@ -e 'import Pkg; Pkg.build()'
        - julia --project=@ -e 'import Pkg; Pkg.status()'
#        - julia --project=@ docs/make.jl
      after_success:
        - julia -e 'import Pkg; Pkg.add("Measurements")'
        - julia -e 'import Pkg; Pkg.add("Unitful")'
        - julia --project=@ -e 'import Pkg; Pkg.add("PyCall")'
        - julia -e 'using Pkg; Pkg.instantiate()'
        - julia --code-coverage test/runtests.jl
        - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
 #       - julia -e 'import Pkg; cd(Pkg.dir("BarycentricLagrangeInterpolation")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
